// This file is auto-generated by @hey-api/openapi-ts

export type AgentCreate = {
    name: string;
    description?: (string | null);
    system_prompt?: string;
    model_name?: string;
    temperature?: number;
    is_active?: boolean;
    tools?: (Array<(string)> | null);
};

export type AgentPublic = {
    name: string;
    description?: (string | null);
    system_prompt?: string;
    model_name?: string;
    temperature?: number;
    is_active?: boolean;
    tools?: (Array<(string)> | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type AgentsPublic = {
    data: Array<AgentPublic>;
    count: number;
};

export type AgentUpdate = {
    name?: (string | null);
    description?: (string | null);
    system_prompt?: (string | null);
    model_name?: (string | null);
    temperature?: (number | null);
    is_active?: (boolean | null);
    tools?: (Array<(string)> | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ConversationCreate = {
    title?: (string | null);
    user_id?: (string | null);
};

export type ConversationPublic = {
    title?: (string | null);
    user_id?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type MessageCreate = {
    role: string;
    content: string;
};

export type MessagePublic = {
    role: string;
    content: string;
    id: string;
    conversation_id: string;
    created_at: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TaskCreate = {
    name: string;
    total_items?: number;
};

export type TaskPublic = {
    name: string;
    total_items?: number;
    id: string;
    status: string;
    processed_items: number;
    error_log: ({
    [key: string]: unknown;
} | null);
    result: ({
    [key: string]: unknown;
} | null);
    created_at: string;
    finished_at: (string | null);
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AgentsReadAgentsData = {
    limit?: number;
    skip?: number;
};

export type AgentsReadAgentsResponse = (AgentsPublic);

export type AgentsCreateAgentData = {
    requestBody: AgentCreate;
};

export type AgentsCreateAgentResponse = (AgentPublic);

export type AgentsReadAgentData = {
    id: string;
};

export type AgentsReadAgentResponse = (AgentPublic);

export type AgentsUpdateAgentData = {
    id: string;
    requestBody: AgentUpdate;
};

export type AgentsUpdateAgentResponse = (AgentPublic);

export type AgentsDeleteAgentData = {
    id: string;
};

export type AgentsDeleteAgentResponse = (AgentPublic);

export type ChatCreateConversationData = {
    requestBody: ConversationCreate;
};

export type ChatCreateConversationResponse = (ConversationPublic);

export type ChatReadMessagesData = {
    conversationId: string;
};

export type ChatReadMessagesResponse = (Array<MessagePublic>);

export type ChatSendMessageData = {
    conversationId: string;
    requestBody: MessageCreate;
};

export type ChatSendMessageResponse = (MessagePublic);

export type ChatStreamChatData = {
    agentId?: (string | null);
    requestBody: MessageCreate;
};

export type ChatStreamChatResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TasksReadTasksData = {
    limit?: number;
    skip?: number;
};

export type TasksReadTasksResponse = (TasksPublic);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskPublic);

export type TasksReadTaskData = {
    id: string;
};

export type TasksReadTaskResponse = (TaskPublic);

export type TasksCancelTaskData = {
    id: string;
};

export type TasksCancelTaskResponse = (TaskPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);