"""add thinking_steps to message

Revision ID: 0ca4c9de965e
Revises: 1a5bc8d0894b
Create Date: 2026-01-16 14:02:57.976415

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0ca4c9de965e'
down_revision = '1a5bc8d0894b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('thinking_steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'thinking_steps')
    # ### end Alembic commands ###
