"""Add standard tables

Revision ID: 16f5984edee9
Revises: d1ecf85e062b
Create Date: 2026-01-16 12:13:07.848444

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '16f5984edee9'
down_revision = 'd1ecf85e062b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
