"""Add is_pinned to conversation

Revision ID: 234842999eeb
Revises: b56de9d8ff6c
Create Date: 2026-01-16 00:11:26.089074

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '234842999eeb'
down_revision = 'b56de9d8ff6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.add_column('agent', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('agent', sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('agent', sa.Column('allowed_departments', sa.JSON(), nullable=True))
    op.add_column('agent', sa.Column('allowed_roles', sa.JSON(), nullable=True))
    op.add_column('agent', sa.Column('execution_mode', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('conversation', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'is_pinned')
    op.drop_column('agent', 'execution_mode')
    op.drop_column('agent', 'allowed_roles')
    op.drop_column('agent', 'allowed_departments')
    op.drop_column('agent', 'visibility')
    op.drop_column('agent', 'category')
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    # ### end Alembic commands ###
