"""Add cascade delete to conversation user_id

Revision ID: 2f20a265bc09
Revises: a8c7316f0cf3
Create Date: 2026-01-13 01:27:19.724767

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2f20a265bc09'
down_revision = 'a8c7316f0cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversation_user_id_fkey'), 'conversation', type_='foreignkey')
    op.create_foreign_key(None, 'conversation', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_user_id_fkey'), 'conversation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
