"""add_table_standard_tables

Revision ID: d1ecf85e062b
Revises: 743f4e823db3
Create Date: 2026-01-16 12:11:50.954469

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd1ecf85e062b'
down_revision = '743f4e823db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
