/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutToolsRouteImport } from './routes/_layout/tools'
import { Route as LayoutTasksRouteImport } from './routes/_layout/tasks'
import { Route as LayoutSkillsRouteImport } from './routes/_layout/skills'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutModelProvidersRouteImport } from './routes/_layout/model-providers'
import { Route as LayoutDataStandardsRouteImport } from './routes/_layout/data-standards'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutToolsIdRouteImport } from './routes/_layout/tools/$id'
import { Route as LayoutDataStandardsIdRouteImport } from './routes/_layout/data-standards/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutToolsRoute = LayoutToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksRoute = LayoutTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSkillsRoute = LayoutSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelProvidersRoute = LayoutModelProvidersRouteImport.update({
  id: '/model-providers',
  path: '/model-providers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDataStandardsRoute = LayoutDataStandardsRouteImport.update({
  id: '/data-standards',
  path: '/data-standards',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutToolsIdRoute = LayoutToolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutToolsRoute,
} as any)
const LayoutDataStandardsIdRoute = LayoutDataStandardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutDataStandardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/agents': typeof LayoutAgentsRoute
  '/data-standards': typeof LayoutDataStandardsRouteWithChildren
  '/model-providers': typeof LayoutModelProvidersRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/tasks': typeof LayoutTasksRoute
  '/tools': typeof LayoutToolsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/data-standards/$id': typeof LayoutDataStandardsIdRoute
  '/tools/$id': typeof LayoutToolsIdRoute
  '/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/agents': typeof LayoutAgentsRoute
  '/data-standards': typeof LayoutDataStandardsRouteWithChildren
  '/model-providers': typeof LayoutModelProvidersRoute
  '/settings': typeof LayoutSettingsRoute
  '/skills': typeof LayoutSkillsRoute
  '/tasks': typeof LayoutTasksRoute
  '/tools': typeof LayoutToolsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/data-standards/$id': typeof LayoutDataStandardsIdRoute
  '/tools/$id': typeof LayoutToolsIdRoute
  '/admin': typeof LayoutAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/agents': typeof LayoutAgentsRoute
  '/_layout/data-standards': typeof LayoutDataStandardsRouteWithChildren
  '/_layout/model-providers': typeof LayoutModelProvidersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/skills': typeof LayoutSkillsRoute
  '/_layout/tasks': typeof LayoutTasksRoute
  '/_layout/tools': typeof LayoutToolsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/data-standards/$id': typeof LayoutDataStandardsIdRoute
  '/_layout/tools/$id': typeof LayoutToolsIdRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/data-standards'
    | '/model-providers'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/tools'
    | '/'
    | '/data-standards/$id'
    | '/tools/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/agents'
    | '/data-standards'
    | '/model-providers'
    | '/settings'
    | '/skills'
    | '/tasks'
    | '/tools'
    | '/'
    | '/data-standards/$id'
    | '/tools/$id'
    | '/admin'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/agents'
    | '/_layout/data-standards'
    | '/_layout/model-providers'
    | '/_layout/settings'
    | '/_layout/skills'
    | '/_layout/tasks'
    | '/_layout/tools'
    | '/_layout/'
    | '/_layout/data-standards/$id'
    | '/_layout/tools/$id'
    | '/_layout/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tools': {
      id: '/_layout/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof LayoutToolsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks': {
      id: '/_layout/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/skills': {
      id: '/_layout/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof LayoutSkillsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/model-providers': {
      id: '/_layout/model-providers'
      path: '/model-providers'
      fullPath: '/model-providers'
      preLoaderRoute: typeof LayoutModelProvidersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/data-standards': {
      id: '/_layout/data-standards'
      path: '/data-standards'
      fullPath: '/data-standards'
      preLoaderRoute: typeof LayoutDataStandardsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/tools/$id': {
      id: '/_layout/tools/$id'
      path: '/$id'
      fullPath: '/tools/$id'
      preLoaderRoute: typeof LayoutToolsIdRouteImport
      parentRoute: typeof LayoutToolsRoute
    }
    '/_layout/data-standards/$id': {
      id: '/_layout/data-standards/$id'
      path: '/$id'
      fullPath: '/data-standards/$id'
      preLoaderRoute: typeof LayoutDataStandardsIdRouteImport
      parentRoute: typeof LayoutDataStandardsRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutDataStandardsRouteChildren {
  LayoutDataStandardsIdRoute: typeof LayoutDataStandardsIdRoute
}

const LayoutDataStandardsRouteChildren: LayoutDataStandardsRouteChildren = {
  LayoutDataStandardsIdRoute: LayoutDataStandardsIdRoute,
}

const LayoutDataStandardsRouteWithChildren =
  LayoutDataStandardsRoute._addFileChildren(LayoutDataStandardsRouteChildren)

interface LayoutToolsRouteChildren {
  LayoutToolsIdRoute: typeof LayoutToolsIdRoute
}

const LayoutToolsRouteChildren: LayoutToolsRouteChildren = {
  LayoutToolsIdRoute: LayoutToolsIdRoute,
}

const LayoutToolsRouteWithChildren = LayoutToolsRoute._addFileChildren(
  LayoutToolsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutAgentsRoute: typeof LayoutAgentsRoute
  LayoutDataStandardsRoute: typeof LayoutDataStandardsRouteWithChildren
  LayoutModelProvidersRoute: typeof LayoutModelProvidersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSkillsRoute: typeof LayoutSkillsRoute
  LayoutTasksRoute: typeof LayoutTasksRoute
  LayoutToolsRoute: typeof LayoutToolsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutAgentsRoute: LayoutAgentsRoute,
  LayoutDataStandardsRoute: LayoutDataStandardsRouteWithChildren,
  LayoutModelProvidersRoute: LayoutModelProvidersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSkillsRoute: LayoutSkillsRoute,
  LayoutTasksRoute: LayoutTasksRoute,
  LayoutToolsRoute: LayoutToolsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
